server:
  port: 28080
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/converter-ms.p12
    key-store-password: 1QXy9zu9sQLVWOr
    key-alias: converterall

spring:
  application:
    name: converter-gateway
  profiles:
    active: local
  cloud:
    gateway:
      routes:
        - id: backend_route
          uri: http://localhost:28081/converter
          predicates:
            - Path=/converter/**
        - id: ui_route
          uri: http://localhost:28082/ui
          predicates:
            - Path=/ui/**

logging:
  file:
    path: ${HOME}/dev/converter/logs
